table Customers
	lineageTag: e720458a-5172-4007-9535-07222b2bf287
	sourceLineageTag: [dbo].[Customers]

	measure 'Customer Count' = DISTINCTCOUNT(Customers[CustomerID])
		formatString: 0
		lineageTag: 1f8a00b3-1829-498d-b484-5314fd7bccaa

		changedProperty = Name

	column CustomerID
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: b101cfb6-3a68-4ac5-ba5f-2da7d3a21745
		sourceLineageTag: CustomerID
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1a4711a3-6736-4b99-a43d-f360cc606914
		sourceLineageTag: CustomerName
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: bb9189b2-3165-4450-a50a-657a783a9904
		sourceLineageTag: Email
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: d0fbb019-bd35-4be1-9342-5ea2beec7638
		sourceLineageTag: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	partition Customers = entity
		mode: directLake
		source
			entityName: Customers
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

